apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mesh 
spec:
  replicas: 65
  template:
    metadata:
      labels:
        app: chunkflow
    spec:
      containers:
        - name: chunkflow
          image: seunglab/chunkflow:mesh
          volumeMounts:
          - name: secrets
            mountPath: "/secrets"
            readOnly: true
          - name: tmp
            mountPath: "/tmp"
            readOnly: false
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args:
              - chunkflow --mip 3 fetch-task -q zfish -v 600 cutout -v gs://jwu-zfish/v1/20200406 --fill-missing --expand-margin-size 1 1 1 mesh --voxel-size 45 5 5 -o gs://jwu-zfish/v1/20200406 --dust-threshold 100 -e 40 --ids "all_neuron_ids.json" delete-task-in-queue
          resources:
            requests:
              memory: 45Gi
          env:
          - name: LC_ALL
            value: "C.UTF-8"
          - name: LANG
            value: "C.UTF-8"
      volumes:
      - name: secrets
        secret:
          secretName: secrets
      - name: tmp
        emptyDir: { medium: "Memory" }
